/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#bb0013",
          red: "#ff3131",
          container: "#e51a22",
          fixed: "#ffdad6",
          "fixed-dim": "#ffb4ab",
        },
        secondary: {
          DEFAULT: "#565e74",
          container: "#dae2fd",
          fixed: "#dae2fd",
          "fixed-dim": "#bec6e0",
        },
        tertiary: {
          DEFAULT: "#4f5d72",
          container: "#67758c",
          fixed: "#d5e3fd",
          "fixed-dim": "#b9c7e0",
        },
        background: "#f7f9fb",
        surface: {
          DEFAULT: "#f7f9fb",
          dim: "#d8dadc",
          bright: "#f7f9fb",
          variant: "#e0e3e5",
          tint: "#c00014",
          container: "#eceef0",
          "container-lowest": "#ffffff",
          "container-low": "#f2f4f6",
          "container-high": "#e6e8ea",
          "container-highest": "#e0e3e5",
        },
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "on-surface-variant": "#5e3f3c",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fdfcff",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#ffb4ab",
        outline: "#926e6a",
        "outline-variant": "#e7bcb8",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
      },
      spacing: {
        unit: "4px",
        "gutter-mobile": "16px",
        "margin-desktop": "64px",
        "gutter-desktop": "24px",
        "margin-mobile": "20px",
        "container-max": "1440px",
      },
      fontFamily: {
        headline: ["Montserrat", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
}
